DROP TABLE IF EXISTS CONTENT_MEDIA;
CREATE TABLE CONTENT_MEDIA
(
    CONTENT_ID BIGINT NOT NULL,
    TYPE_ID BIGINT NOT NULL,
    MEDIA BYTEA,
    CONSTRAINT PK_CONTENT_TYPE PRIMARY KEY (CONTENT_ID, TYPE_ID),
    CONSTRAINT FK_CONTENT_TYPE FOREIGN KEY (TYPE_ID) REFERENCES MEDIA_TYPE (ID),
    CONSTRAINT FK_CONTENT_MEDIA_CONTENT FOREIGN KEY (CONTENT_ID) REFERENCES CONTENT (ID)
);