DROP TABLE IF EXISTS SUBTITLE;
CREATE TABLE SUBTITLE
(
    ID SERIAL PRIMARY KEY NOT NULL,
    LINE VARCHAR(4000),
    TO_BEGIN BIGINT,
    FROM_END BIGINT,
    MEDIA_SUBTITLE_ID BIGINT,
    CONSTRAINT FK_SUBTITLE FOREIGN KEY (MEDIA_SUBTITLE_ID) REFERENCES MEDIA_SUBTITLE (ID)
);