DROP TABLE IF EXISTS CONTENT_RECOMMENDED;
CREATE TABLE CONTENT_RECOMMENDED
(
    ID SERIAL PRIMARY KEY NOT NULL,
    CONTENT_ID BIGINT,
    CONSTRAINT FK_CONTENT_RECOMMENDED_CONTENT FOREIGN KEY (CONTENT_ID) REFERENCES CONTENT (ID)
);