DROP TABLE IF EXISTS CONTENT_LANGUAGE;
CREATE TABLE CONTENT_LANGUAGE
(
    CONTENT_ID BIGINT,
    LANGUAGE_ID BIGINT,
    CONSTRAINT PK_CONTENT_LANGUAGE PRIMARY KEY (CONTENT_ID, LANGUAGE_ID),
    CONSTRAINT FK_CONTENT_LANGUAGE_CONTENT FOREIGN KEY (CONTENT_ID) REFERENCES CONTENT (ID),
    CONSTRAINT FK_CONTENT_LANGUAGE_LANGUAGES FOREIGN KEY (LANGUAGE_ID) REFERENCES LANGUAGES (ID)
);