DROP TABLE IF EXISTS CONTENT_TYPE;
CREATE TABLE CONTENT_TYPE
(
    CONTENT_ID BIGINT,
    TYPE_ID BIGINT,
    CONSTRAINT PK_CONTENT_TYPE_CONTENT PRIMARY KEY (CONTENT_ID, TYPE_ID),
    CONSTRAINT FK_CONTENT_TYPE_CONTENT FOREIGN KEY (CONTENT_ID) REFERENCES CONTENT (ID),
    CONSTRAINT FK_CONTENT_TYPE_MEDIA_TYPE FOREIGN KEY (CONTENT_ID) REFERENCES MEDIA_TYPE (ID)
);