DROP TABLE IF EXISTS MARK;
CREATE TABLE MARK
(
    ID SERIAL PRIMARY KEY NOT NULL,
    SETTING_ID BIGINT,
    STARTS BIGINT,
    ENDS BIGINT,
    REPEAT BIGINT,
    DELAY BIGINT,
    CONSTRAINT FK_SETTING_MARK FOREIGN KEY (SETTING_ID) REFERENCES SETTING (ID)
);