DROP TABLE IF EXISTS USERS;
CREATE TABLE USERS
(
    ID SERIAL PRIMARY KEY NOT NULL,
    NAME VARCHAR(255),
    PHONE VARCHAR(11),
    PASSWORD VARCHAR(255),
    BIRTH_DATE DATE,
    ROLE VARCHAR(255),
    UNIQUE (PHONE)
);