INSERT INTO LANGUAGES (ID, LANGUAGE, CODE2) VALUES (1, 'Russian', 'RU');
INSERT INTO LANGUAGES (ID, LANGUAGE, CODE2) VALUES (2, 'English', 'EN');
INSERT INTO LANGUAGES (ID, LANGUAGE, CODE2) VALUES (3, 'German', 'DE');
INSERT INTO LANGUAGES (ID, LANGUAGE, CODE2) VALUES (4, 'French', 'FR');
INSERT INTO LANGUAGES (ID, LANGUAGE, CODE2) VALUES (5, 'Spanish', 'ES');
INSERT INTO LANGUAGES (ID, LANGUAGE, CODE2) VALUES (6, 'Italian', 'IT');