DROP TABLE IF EXISTS CONTENT;
CREATE TABLE CONTENT
(
    ID SERIAL PRIMARY KEY NOT NULL,
    NAME VARCHAR(255),
    LIMIT_ID BIGINT,
    ARTIST VARCHAR(255),
    USER_ID BIGINT,
    CREATE_DATE DATE,
    LANGUAGE_ID BIGINT,
    CONSTRAINT PK_CONTENT_AGE_LIMIT FOREIGN KEY (LIMIT_ID) REFERENCES AGE_LIMIT (ID),
    CONSTRAINT PK_CONTENT_USERS FOREIGN KEY (USER_ID) REFERENCES USERS (ID),
    CONSTRAINT PK_CONTENT_LANGUAGE FOREIGN KEY (LANGUAGE_ID) REFERENCES LANGUAGES (ID)
);